apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleproject
  name: simpleproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleproject
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleproject
    spec:
      containers:
      - image: sklalani/simpleproject:latest
        name: simpleproject
        resources: {}
status: {}
