apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleproject
  name: simpleproject
spec:
  type: NodePort
  ports:
  - name: "simpleproject-service"
    port: 5000
    targetPort: 80
    nodePort: 31011
  selector:
    app: simpleproject


